impr(UTAPI-83): Add warp 10 release workflow
scality/utapi pull request #1270
Opened 2022-10-05 19:01 UTC by tmacro

2022-10-05 19:01 UTC, bert-e commented
# Hello tmacro,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/utapi/doc/user).





*Status report is not available.*

2022-10-05 19:01 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue UTAPI-83 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `7.10.10`

* `8.1.9`


Please check the `Fix Version/s` of UTAPI-83, or the target
branch of this pull request.

2022-10-05 19:03 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/UTAPI-83/provide_warp10_image` into
`development/7.10`
* [w/8.1/improvement/UTAPI-83/provide_warp10_image](https://github.com/scality/utapi/compare/development/8.1...w/8.1/improvement/UTAPI-83/provide_warp10_image) will be merged into `development/8.1` 



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-10-05 19:03 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-10-05 19:06 UTC, naren-rajendran approved these changes

2022-10-05 19:40 UTC, jonathan-gramain approved these changes

2022-10-05 19:40 UTC, jonathan-gramain commented on .github/workflows/release-warp10.yaml
> +          name: Release scality/warp10:${{ github.event.inputs.tag }}
This looks more accurate but please correct my suggestion if it is not correct:

```suggestion
          name: Release registry.scality.com/utapi/warp10:${{ github.event.inputs.tag }}-warp10
```

2022-10-05 20:17 UTC, bert-e commented
# History mismatch



Merge commit #1a6f3703651e5d27d37d6b5d0f93f142abbec7a3 on the integration branch
`w/8.1/improvement/UTAPI-83/provide_warp10_image` is merging a branch which is neither the current
branch `improvement/UTAPI-83/provide_warp10_image` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `improvement/UTAPI-83/provide_warp10_image` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-10-05 20:17 UTC, tmacro commented
/reset

2022-10-05 20:17 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2022-10-05 20:17 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/UTAPI-83/provide_warp10_image` into
`development/7.10`
* [w/8.1/improvement/UTAPI-83/provide_warp10_image](https://github.com/scality/utapi/compare/development/8.1...w/8.1/improvement/UTAPI-83/provide_warp10_image) will be merged into `development/8.1` 



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-10-05 20:17 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-10-07 12:40 UTC, Emylou-s requested changes
There seems to be significant changes between the dockerfile used in utapi repo and the one used in federation.
Among others one I can see is the line in Federation : 

`# Install protobuf extestion
ADD ./warp10-ext-protobuf-1.1.0-uberjar.jar /opt/warp10/lib/
`

How can we make sure the generated image will be compatible with what's built in Federation.

I have the feeling that there will be significant work needed in Federation to match this new image.

2022-10-07 12:40 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @emylou-s

2022-10-07 16:46 UTC, tmacro commented
The image is compatible with the one in federation. The only difference aside from the bump to the protobuf extension is the
inclusion of the sensision prometheus exporter which is disabled by default.

2022-10-10 11:13 UTC, Emylou-s approved these changes

2022-10-10 11:13 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-10-10 16:49 UTC, tmacro commented
/approve

2022-10-10 16:49 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-10-10 16:49 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue UTAPI-83.

Goodbye tmacro.

2022-10-10 16:49 UTC, merged