ft(S3C-3000): Add Warp 10 client
scality/utapi pull request #480
Opened 2020-06-17 00:23 UTC by tmacro

2020-06-17 00:47 UTC, rahulreddy commented on tests/functional/v2/warp10/testClient.js
> +describe.only('Test Warp Client', () => {
Looks like a rouge `.only` made it here.

2020-06-17 00:53 UTC, miniscruff requested changes
Just Rahul's comment

2020-06-17 03:28 UTC, miniscruff approved these changes

2020-06-18 12:05 UTC, naren-rajendran approved these changes

2020-06-18 20:11 UTC, bert-e commented
# Hello tmacro,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/utapi/bert-e/doc/user).





*Status report is not available.*

2020-06-18 20:12 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-3000_Add_warp10_client` into
`development/7.7`
* [w/7.8/feature/S3C-3000_Add_warp10_client](https://github.com/scality/utapi/compare/development/7.8...w/7.8/feature/S3C-3000_Add_warp10_client) will be merged into `development/7.8` (pull request #482)
* [w/8.1/feature/S3C-3000_Add_warp10_client](https://github.com/scality/utapi/compare/development/8.1...w/8.1/feature/S3C-3000_Add_warp10_client) will be merged into `development/8.1` (pull request #483)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.5`
* `development/7.6`
* `stabilization/7.4.6`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-06-18 20:12 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @tmacro.

2020-06-18 20:12 UTC, bert-e commented
# History mismatch



Merge commit #81f2257566a3890022bddbc0511925ac1bac5fc6 on the integration branch
`w/7.8/feature/S3C-3000_Add_warp10_client` is merging a branch which is neither the current
branch `feature/S3C-3000_Add_warp10_client` nor the development branch
`development/7.8`.

It is likely due to a rebase of the branch `feature/S3C-3000_Add_warp10_client` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-06-18 20:30 UTC, bert-e commented
# History mismatch



Merge commit #b4c102e904e3288fe708b3b3785a4d88358cd210 on the integration branch
`w/7.8/feature/S3C-3000_Add_warp10_client` is merging a branch which is neither the current
branch `feature/S3C-3000_Add_warp10_client` nor the development branch
`development/7.8`.

It is likely due to a rebase of the branch `feature/S3C-3000_Add_warp10_client` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-06-18 20:30 UTC, tmacro commented
/reset

2020-06-18 20:30 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-06-18 20:31 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-3000_Add_warp10_client` into
`development/7.7`
* [w/7.8/feature/S3C-3000_Add_warp10_client](https://github.com/scality/utapi/compare/development/7.8...w/7.8/feature/S3C-3000_Add_warp10_client) will be merged into `development/7.8` (pull request #488)
* [w/8.1/feature/S3C-3000_Add_warp10_client](https://github.com/scality/utapi/compare/development/8.1...w/8.1/feature/S3C-3000_Add_warp10_client) will be merged into `development/8.1` (pull request #489)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.5`
* `development/7.6`
* `stabilization/7.4.6`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-06-18 20:31 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @tmacro.

2020-06-18 20:31 UTC, tmacro commented
/approve

2020-06-18 20:33 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/7.8`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.5`
* `development/7.6`
* `stabilization/7.4.6`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-06-18 20:33 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/7.8`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `development/7.5`
* `development/7.6`
* `stabilization/7.4.6`



Please check the status of the associated issue S3C-3000.

Goodbye tmacro.

2020-06-18 20:34 UTC, merged